name: datify
description: An extensible library that provides the functionality of the parsing strings in different formats to extract dates.
version: 1.0.2
repository: https://github.com/mitryp/datifyDart

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: any
  test: ^1.16.0
