name: datify
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: any
  test: ^1.16.0
