name: datify
description: An extensible library providing the functionality of parsing strings to extract dates in different formats.
version: 1.2.0
repository: https://github.com/mitryp/datifyDart
issue_tracker: https://github.com/mitryp/datifyDart/issues/

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
