name: datify
description: An extensible library providing the functionality of parsing strings to extract dates in different formats.
version: 1.1.6
repository: https://github.com/mitryp/datifyDart
issue_tracker: https://github.com/mitryp/datifyDart/issues/

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
